"""initial_schema_postgres

Revision ID: 97720ec042a7
Revises: 
Create Date: 2026-08-22 12:42:27.404254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97720ec042a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('log_id'),
    sa.UniqueConstraint('event_id'),
    sa.UniqueConstraint('tenant_id', 'sequence_number', name='uq_audit_log_tenant_seq')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_sequence_number'), 'audit_logs', ['sequence_number'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('change_relationships',
    sa.Column('relationship_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.Enum('CHANGE', 'PULL_REQUEST', 'COMMIT', 'TEST', 'DEPLOYMENT', 'APPROVAL', 'AUTHORIZATION', 'EVIDENCE', name='entitytype'), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.Enum('CHANGE', 'PULL_REQUEST', 'COMMIT', 'TEST', 'DEPLOYMENT', 'APPROVAL', 'AUTHORIZATION', 'EVIDENCE', name='entitytype'), nullable=False),
    sa.Column('relationship_type', sa.Enum('ASSOCIATED_WITH', 'TRIGGERS', 'IMPLEMENTS', 'TESTS', 'APPROVES', 'AUTHORIZES', 'GENERATES_EVIDENCE', 'CONTAINS', name='relationshiptype'), nullable=False),
    sa.PrimaryKeyConstraint('relationship_id')
    )
    op.create_index(op.f('ix_change_relationships_source_id'), 'change_relationships', ['source_id'], unique=False)
    op.create_index(op.f('ix_change_relationships_target_id'), 'change_relationships', ['target_id'], unique=False)
    op.create_table('connectors',
    sa.Column('connector_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('connector_id')
    )
    op.create_table('environments',
    sa.Column('environment_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('DEVELOPMENT', 'TEST', 'STAGING', 'PRODUCTION', name='ormenvtype'), nullable=False),
    sa.Column('criticality', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('environment_id')
    )
    op.create_index(op.f('ix_environments_tenant_id'), 'environments', ['tenant_id'], unique=False)
    op.create_table('frameworks',
    sa.Column('framework_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('authority', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('framework_id')
    )
    op.create_table('repositories',
    sa.Column('repository_id', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('organization', sa.String(length=100), nullable=False),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('production_branch', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('repository_id')
    )
    op.create_index(op.f('ix_repositories_external_id'), 'repositories', ['external_id'], unique=False)
    op.create_table('users',
    sa.Column('internal_user_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('internal_user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('applications',
    sa.Column('application_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('environment_id', sa.String(length=100), nullable=False),
    sa.Column('criticality', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.environment_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_index(op.f('ix_applications_environment_id'), 'applications', ['environment_id'], unique=False)
    op.create_index(op.f('ix_applications_tenant_id'), 'applications', ['tenant_id'], unique=False)
    op.create_table('connector_accounts',
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('connector_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.connector_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_connector_accounts_connector_id'), 'connector_accounts', ['connector_id'], unique=False)
    op.create_index(op.f('ix_connector_accounts_tenant_id'), 'connector_accounts', ['tenant_id'], unique=False)
    op.create_table('controls',
    sa.Column('control_id', sa.String(length=50), nullable=False),
    sa.Column('framework_id', sa.String(length=50), nullable=False),
    sa.Column('criterion', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lifecycle_stage', sa.String(length=100), nullable=False),
    sa.Column('applicability', sa.String(length=100), nullable=False),
    sa.Column('evidence_requirements', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.framework_id'], ),
    sa.PrimaryKeyConstraint('control_id')
    )
    op.create_index(op.f('ix_controls_criterion'), 'controls', ['criterion'], unique=False)
    op.create_index(op.f('ix_controls_framework_id'), 'controls', ['framework_id'], unique=False)
    op.create_table('identity_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('internal_user_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_user_id', sa.String(length=100), nullable=False),
    sa.Column('external_username', sa.String(length=100), nullable=False),
    sa.Column('external_reference', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['internal_user_id'], ['users.internal_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source', 'external_user_id', name='uq_identity_link_tenant_source_ext_id')
    )
    op.create_index(op.f('ix_identity_links_external_user_id'), 'identity_links', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_identity_links_internal_user_id'), 'identity_links', ['internal_user_id'], unique=False)
    op.create_index(op.f('ix_identity_links_tenant_id'), 'identity_links', ['tenant_id'], unique=False)
    op.create_table('changes',
    sa.Column('change_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('change_type', sa.Enum('NORMAL', 'STANDARD', 'EMERGENCY', name='ormchangetype'), nullable=False),
    sa.Column('requester_id', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.String(length=100), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('environment_id', sa.String(length=100), nullable=False),
    sa.Column('application_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('planned_start', sa.DateTime(), nullable=True),
    sa.Column('planned_end', sa.DateTime(), nullable=True),
    sa.Column('implemented_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.environment_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.internal_user_id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.internal_user_id'], ),
    sa.PrimaryKeyConstraint('change_id')
    )
    op.create_index(op.f('ix_changes_application_id'), 'changes', ['application_id'], unique=False)
    op.create_index(op.f('ix_changes_environment_id'), 'changes', ['environment_id'], unique=False)
    op.create_index(op.f('ix_changes_external_id'), 'changes', ['external_id'], unique=False)
    op.create_index(op.f('ix_changes_owner_id'), 'changes', ['owner_id'], unique=False)
    op.create_index(op.f('ix_changes_requester_id'), 'changes', ['requester_id'], unique=False)
    op.create_index(op.f('ix_changes_tenant_id'), 'changes', ['tenant_id'], unique=False)
    op.create_table('compliance_checks',
    sa.Column('check_id', sa.String(length=50), nullable=False),
    sa.Column('control_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('lifecycle_stage', sa.String(length=100), nullable=False),
    sa.Column('required_data', sa.JSON(), nullable=False),
    sa.Column('evaluation_logic', sa.JSON(), nullable=False),
    sa.Column('evidence_requirements', sa.JSON(), nullable=False),
    sa.Column('reremediation_guidance', sa.Text(), nullable=True),
    sa.Column('applicability', sa.String(length=100), nullable=False),
    sa.Column('result_types', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['controls.control_id'], ),
    sa.PrimaryKeyConstraint('check_id')
    )
    op.create_index(op.f('ix_compliance_checks_control_id'), 'compliance_checks', ['control_id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('sync_run_id', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('records_synced', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['connector_accounts.account_id'], ),
    sa.PrimaryKeyConstraint('sync_run_id')
    )
    op.create_index(op.f('ix_sync_runs_account_id'), 'sync_runs', ['account_id'], unique=False)
    op.create_table('approvals',
    sa.Column('approval_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('change_id', sa.String(length=100), nullable=False),
    sa.Column('approver_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.internal_user_id'], ),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_index(op.f('ix_approvals_approver_id'), 'approvals', ['approver_id'], unique=False)
    op.create_index(op.f('ix_approvals_change_id'), 'approvals', ['change_id'], unique=False)
    op.create_index(op.f('ix_approvals_tenant_id'), 'approvals', ['tenant_id'], unique=False)
    op.create_table('authorizations',
    sa.Column('authorization_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('change_id', sa.String(length=100), nullable=False),
    sa.Column('authorized_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('authorized_at', sa.DateTime(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by'], ['users.internal_user_id'], ),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.PrimaryKeyConstraint('authorization_id')
    )
    op.create_index(op.f('ix_authorizations_authorized_by'), 'authorizations', ['authorized_by'], unique=False)
    op.create_index(op.f('ix_authorizations_change_id'), 'authorizations', ['change_id'], unique=False)
    op.create_index(op.f('ix_authorizations_tenant_id'), 'authorizations', ['tenant_id'], unique=False)
    op.create_table('check_results',
    sa.Column('result_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('check_id', sa.String(length=50), nullable=False),
    sa.Column('change_id', sa.String(length=100), nullable=False),
    sa.Column('result', sa.Enum('PASS', 'FAIL', 'INSUFFICIENT_DATA', 'NOT_APPLICABLE', 'ERROR', name='ormcheckresulttype'), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('evaluation_inputs', sa.JSON(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.ForeignKeyConstraint(['check_id'], ['compliance_checks.check_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_check_results_change_id'), 'check_results', ['change_id'], unique=False)
    op.create_index(op.f('ix_check_results_check_id'), 'check_results', ['check_id'], unique=False)
    op.create_index(op.f('ix_check_results_tenant_id'), 'check_results', ['tenant_id'], unique=False)
    op.create_table('deployments',
    sa.Column('deployment_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('change_id', sa.String(length=100), nullable=True),
    sa.Column('application_id', sa.String(length=100), nullable=False),
    sa.Column('environment_id', sa.String(length=100), nullable=False),
    sa.Column('repository_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('commit_id', sa.String(length=100), nullable=False),
    sa.Column('deployed_by', sa.String(length=100), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.ForeignKeyConstraint(['deployed_by'], ['users.internal_user_id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.environment_id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.repository_id'], ),
    sa.PrimaryKeyConstraint('deployment_id')
    )
    op.create_index(op.f('ix_deployments_application_id'), 'deployments', ['application_id'], unique=False)
    op.create_index(op.f('ix_deployments_change_id'), 'deployments', ['change_id'], unique=False)
    op.create_index(op.f('ix_deployments_deployed_by'), 'deployments', ['deployed_by'], unique=False)
    op.create_index(op.f('ix_deployments_environment_id'), 'deployments', ['environment_id'], unique=False)
    op.create_index(op.f('ix_deployments_repository_id'), 'deployments', ['repository_id'], unique=False)
    op.create_index(op.f('ix_deployments_tenant_id'), 'deployments', ['tenant_id'], unique=False)
    op.create_table('evidence_metadata',
    sa.Column('evidence_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('change_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('storage_reference', sa.String(length=200), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_metadata_change_id'), 'evidence_metadata', ['change_id'], unique=False)
    op.create_index(op.f('ix_evidence_metadata_tenant_id'), 'evidence_metadata', ['tenant_id'], unique=False)
    op.create_table('exceptions',
    sa.Column('exception_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('control_id', sa.String(length=50), nullable=False),
    sa.Column('change_id', sa.String(length=100), nullable=True),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.internal_user_id'], ),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.ForeignKeyConstraint(['control_id'], ['controls.control_id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.internal_user_id'], ),
    sa.PrimaryKeyConstraint('exception_id')
    )
    op.create_index(op.f('ix_exceptions_approved_by'), 'exceptions', ['approved_by'], unique=False)
    op.create_index(op.f('ix_exceptions_change_id'), 'exceptions', ['change_id'], unique=False)
    op.create_index(op.f('ix_exceptions_control_id'), 'exceptions', ['control_id'], unique=False)
    op.create_index(op.f('ix_exceptions_requested_by'), 'exceptions', ['requested_by'], unique=False)
    op.create_index(op.f('ix_exceptions_tenant_id'), 'exceptions', ['tenant_id'], unique=False)
    op.create_table('findings',
    sa.Column('finding_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('check_id', sa.String(length=50), nullable=False),
    sa.Column('control_id', sa.String(length=50), nullable=False),
    sa.Column('change_id', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.ForeignKeyConstraint(['check_id'], ['compliance_checks.check_id'], ),
    sa.ForeignKeyConstraint(['control_id'], ['controls.control_id'], ),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_index(op.f('ix_findings_change_id'), 'findings', ['change_id'], unique=False)
    op.create_index(op.f('ix_findings_check_id'), 'findings', ['check_id'], unique=False)
    op.create_index(op.f('ix_findings_control_id'), 'findings', ['control_id'], unique=False)
    op.create_index(op.f('ix_findings_tenant_id'), 'findings', ['tenant_id'], unique=False)
    op.create_table('tests',
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('change_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('pipeline_id', sa.String(length=150), nullable=False),
    sa.Column('commit_id', sa.String(length=100), nullable=False),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'CANCELLED', 'UNKNOWN', name='ormteststatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('evidence_reference', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_index(op.f('ix_tests_change_id'), 'tests', ['change_id'], unique=False)
    op.create_index(op.f('ix_tests_tenant_id'), 'tests', ['tenant_id'], unique=False)
    op.create_table('check_result_evidence_association',
    sa.Column('result_id', sa.String(length=100), nullable=False),
    sa.Column('evidence_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_metadata.evidence_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_id'], ['check_results.result_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id', 'evidence_id')
    )
    op.create_table('remediation_tasks',
    sa.Column('task_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('finding_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.finding_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_remediation_tasks_finding_id'), 'remediation_tasks', ['finding_id'], unique=False)
    op.create_index(op.f('ix_remediation_tasks_tenant_id'), 'remediation_tasks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remediation_tasks_tenant_id'), table_name='remediation_tasks')
    op.drop_index(op.f('ix_remediation_tasks_finding_id'), table_name='remediation_tasks')
    op.drop_table('remediation_tasks')
    op.drop_table('check_result_evidence_association')
    op.drop_index(op.f('ix_tests_tenant_id'), table_name='tests')
    op.drop_index(op.f('ix_tests_change_id'), table_name='tests')
    op.drop_table('tests')
    op.drop_index(op.f('ix_findings_tenant_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_control_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_check_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_change_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_exceptions_tenant_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_requested_by'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_control_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_change_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_approved_by'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_evidence_metadata_tenant_id'), table_name='evidence_metadata')
    op.drop_index(op.f('ix_evidence_metadata_change_id'), table_name='evidence_metadata')
    op.drop_table('evidence_metadata')
    op.drop_index(op.f('ix_deployments_tenant_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_repository_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_environment_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_deployed_by'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_change_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_application_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_check_results_tenant_id'), table_name='check_results')
    op.drop_index(op.f('ix_check_results_check_id'), table_name='check_results')
    op.drop_index(op.f('ix_check_results_change_id'), table_name='check_results')
    op.drop_table('check_results')
    op.drop_index(op.f('ix_authorizations_tenant_id'), table_name='authorizations')
    op.drop_index(op.f('ix_authorizations_change_id'), table_name='authorizations')
    op.drop_index(op.f('ix_authorizations_authorized_by'), table_name='authorizations')
    op.drop_table('authorizations')
    op.drop_index(op.f('ix_approvals_tenant_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_change_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_approver_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_sync_runs_account_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_compliance_checks_control_id'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    op.drop_index(op.f('ix_changes_tenant_id'), table_name='changes')
    op.drop_index(op.f('ix_changes_requester_id'), table_name='changes')
    op.drop_index(op.f('ix_changes_owner_id'), table_name='changes')
    op.drop_index(op.f('ix_changes_external_id'), table_name='changes')
    op.drop_index(op.f('ix_changes_environment_id'), table_name='changes')
    op.drop_index(op.f('ix_changes_application_id'), table_name='changes')
    op.drop_table('changes')
    op.drop_index(op.f('ix_identity_links_tenant_id'), table_name='identity_links')
    op.drop_index(op.f('ix_identity_links_internal_user_id'), table_name='identity_links')
    op.drop_index(op.f('ix_identity_links_external_user_id'), table_name='identity_links')
    op.drop_table('identity_links')
    op.drop_index(op.f('ix_controls_framework_id'), table_name='controls')
    op.drop_index(op.f('ix_controls_criterion'), table_name='controls')
    op.drop_table('controls')
    op.drop_index(op.f('ix_connector_accounts_tenant_id'), table_name='connector_accounts')
    op.drop_index(op.f('ix_connector_accounts_connector_id'), table_name='connector_accounts')
    op.drop_table('connector_accounts')
    op.drop_index(op.f('ix_applications_tenant_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_environment_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_repositories_external_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_table('frameworks')
    op.drop_index(op.f('ix_environments_tenant_id'), table_name='environments')
    op.drop_table('environments')
    op.drop_table('connectors')
    op.drop_index(op.f('ix_change_relationships_target_id'), table_name='change_relationships')
    op.drop_index(op.f('ix_change_relationships_source_id'), table_name='change_relationships')
    op.drop_table('change_relationships')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_sequence_number'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
