"""sync_schema_changes

Revision ID: cbabf4052efa
Revises: 97720ec042a7
Create Date: 2026-08-31 12:53:05.044250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'cbabf4052efa'
down_revision: Union[str, Sequence[str], None] = '97720ec042a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_approvals',
    sa.Column('approval_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('change_id', sa.String(length=100), nullable=False),
    sa.Column('approver_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.internal_user_id'], ),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_index(op.f('ix_change_approvals_approver_id'), 'change_approvals', ['approver_id'], unique=False)
    op.create_index(op.f('ix_change_approvals_change_id'), 'change_approvals', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_approvals_tenant_id'), 'change_approvals', ['tenant_id'], unique=False)
    op.create_table('change_authorizations',
    sa.Column('authorization_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('change_id', sa.String(length=100), nullable=False),
    sa.Column('authorized_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('authorized_at', sa.DateTime(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by'], ['users.internal_user_id'], ),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.PrimaryKeyConstraint('authorization_id')
    )
    op.create_index(op.f('ix_change_authorizations_authorized_by'), 'change_authorizations', ['authorized_by'], unique=False)
    op.create_index(op.f('ix_change_authorizations_change_id'), 'change_authorizations', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_authorizations_tenant_id'), 'change_authorizations', ['tenant_id'], unique=False)
    op.create_table('change_check_results',
    sa.Column('result_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('check_id', sa.String(length=50), nullable=False),
    sa.Column('change_id', sa.String(length=100), nullable=False),
    sa.Column('result', sa.Enum('PASS', 'FAIL', 'INSUFFICIENT_DATA', 'NOT_APPLICABLE', 'ERROR', name='ormcheckresulttype'), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('evaluation_inputs', sa.JSON(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.ForeignKeyConstraint(['check_id'], ['compliance_checks.check_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_change_check_results_change_id'), 'change_check_results', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_check_results_check_id'), 'change_check_results', ['check_id'], unique=False)
    op.create_index(op.f('ix_change_check_results_tenant_id'), 'change_check_results', ['tenant_id'], unique=False)
    op.create_table('change_decisions',
    sa.Column('decision_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('change_id', sa.String(length=100), nullable=False),
    sa.Column('decision_status', sa.String(length=50), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('policy_version', sa.String(length=50), nullable=False),
    sa.Column('applicable_check_count', sa.Integer(), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('insufficient_data_count', sa.Integer(), nullable=False),
    sa.Column('not_applicable_count', sa.Integer(), nullable=False),
    sa.Column('critical_failure_count', sa.Integer(), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('remediation_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index(op.f('ix_change_decisions_change_id'), 'change_decisions', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_decisions_tenant_id'), 'change_decisions', ['tenant_id'], unique=False)
    op.create_table('change_deployments',
    sa.Column('deployment_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('change_id', sa.String(length=100), nullable=True),
    sa.Column('application_id', sa.String(length=100), nullable=False),
    sa.Column('environment_id', sa.String(length=100), nullable=False),
    sa.Column('repository_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('commit_id', sa.String(length=100), nullable=False),
    sa.Column('deployed_by', sa.String(length=100), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.ForeignKeyConstraint(['deployed_by'], ['users.internal_user_id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.environment_id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.repository_id'], ),
    sa.PrimaryKeyConstraint('deployment_id')
    )
    op.create_index(op.f('ix_change_deployments_application_id'), 'change_deployments', ['application_id'], unique=False)
    op.create_index(op.f('ix_change_deployments_change_id'), 'change_deployments', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_deployments_deployed_by'), 'change_deployments', ['deployed_by'], unique=False)
    op.create_index(op.f('ix_change_deployments_environment_id'), 'change_deployments', ['environment_id'], unique=False)
    op.create_index(op.f('ix_change_deployments_repository_id'), 'change_deployments', ['repository_id'], unique=False)
    op.create_index(op.f('ix_change_deployments_tenant_id'), 'change_deployments', ['tenant_id'], unique=False)
    op.create_table('change_evidence',
    sa.Column('evidence_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('change_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_record_id', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.Column('check_id', sa.String(length=100), nullable=True),
    sa.Column('finding_id', sa.String(length=100), nullable=True),
    sa.Column('remediation_id', sa.String(length=100), nullable=True),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('storage_reference', sa.String(length=200), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('freshness_status', sa.String(length=50), nullable=False),
    sa.Column('integrity_status', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.PrimaryKeyConstraint('evidence_id'),
    sa.UniqueConstraint('tenant_id', 'source', 'source_record_id', 'evidence_type', 'version', name='uq_tenant_source_record_type_version')
    )
    op.create_index(op.f('ix_change_evidence_change_id'), 'change_evidence', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_evidence_tenant_id'), 'change_evidence', ['tenant_id'], unique=False)
    op.create_table('change_rollbacks',
    sa.Column('rollback_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('change_id', sa.String(length=100), nullable=False),
    sa.Column('rollback_plan', sa.Text(), nullable=True),
    sa.Column('rollback_tested', sa.Boolean(), nullable=False),
    sa.Column('rollback_reference', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.PrimaryKeyConstraint('rollback_id')
    )
    op.create_index(op.f('ix_change_rollbacks_change_id'), 'change_rollbacks', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_rollbacks_tenant_id'), 'change_rollbacks', ['tenant_id'], unique=False)
    op.create_table('change_tests',
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('change_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('pipeline_id', sa.String(length=150), nullable=False),
    sa.Column('commit_id', sa.String(length=100), nullable=False),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'CANCELLED', 'UNKNOWN', name='ormteststatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('evidence_reference', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_index(op.f('ix_change_tests_change_id'), 'change_tests', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_tests_tenant_id'), 'change_tests', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_deployments_application_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_change_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_deployed_by'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_environment_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_repository_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_tenant_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_evidence_metadata_change_id'), table_name='evidence_metadata')
    op.drop_index(op.f('ix_evidence_metadata_tenant_id'), table_name='evidence_metadata')
    op.drop_table('evidence_metadata')
    op.drop_index(op.f('ix_tests_change_id'), table_name='tests')
    op.drop_index(op.f('ix_tests_tenant_id'), table_name='tests')
    op.drop_table('tests')
    op.drop_index(op.f('ix_approvals_approver_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_change_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_tenant_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_check_results_change_id'), table_name='check_results')
    op.drop_index(op.f('ix_check_results_check_id'), table_name='check_results')
    op.drop_index(op.f('ix_check_results_tenant_id'), table_name='check_results')
    op.drop_table('check_results')
    op.drop_index(op.f('ix_authorizations_authorized_by'), table_name='authorizations')
    op.drop_index(op.f('ix_authorizations_change_id'), table_name='authorizations')
    op.drop_index(op.f('ix_authorizations_tenant_id'), table_name='authorizations')
    op.drop_table('authorizations')
    op.add_column('change_relationships', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.add_column('change_relationships', sa.Column('evidence_reference', sa.String(length=200), nullable=True))
    op.add_column('change_relationships', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('change_relationships', sa.Column('correlation_method', sa.String(length=100), nullable=True))
    op.add_column('change_relationships', sa.Column('correlation_evidence', sa.Text(), nullable=True))
    op.add_column('change_relationships', sa.Column('confidence', sa.Float(), nullable=False))
    op.add_column('change_relationships', sa.Column('relationship_state', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_change_relationships_tenant_id'), 'change_relationships', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_change_relationship_unique', 'change_relationships', ['tenant_id', 'source_type', 'source_id', 'relationship_type', 'target_type', 'target_id'])
    op.add_column('changes', sa.Column('is_emergency', sa.Boolean(), nullable=False))
    op.add_column('changes', sa.Column('emergency_reason', sa.Text(), nullable=True))
    op.add_column('changes', sa.Column('emergency_approved_by', sa.String(length=100), nullable=True))
    op.add_column('changes', sa.Column('emergency_retro_approved', sa.Boolean(), nullable=True))
    op.add_column('changes', sa.Column('state_hash', sa.String(length=64), nullable=True))
    op.add_column('changes', sa.Column('previous_state_hash', sa.String(length=64), nullable=True))
    op.add_column('changes', sa.Column('last_observed_at', sa.DateTime(), nullable=True))
    op.add_column('changes', sa.Column('last_evaluated_at', sa.DateTime(), nullable=True))
    op.add_column('changes', sa.Column('monitoring_status', sa.String(length=50), nullable=True))
    op.drop_constraint(None, 'check_result_evidence_association', type_='foreignkey')
    op.drop_constraint(None, 'check_result_evidence_association', type_='foreignkey')
    op.create_foreign_key(None, 'check_result_evidence_association', 'change_evidence', ['evidence_id'], ['evidence_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'check_result_evidence_association', 'change_check_results', ['result_id'], ['result_id'], ondelete='CASCADE')
    op.add_column('findings', sa.Column('check_result_id', sa.String(length=100), nullable=True))
    op.add_column('findings', sa.Column('evidence_ids', sa.JSON(), nullable=False))
    op.add_column('remediation_tasks', sa.Column('remediation_id', sa.String(length=100), nullable=True))
    op.add_column('remediation_tasks', sa.Column('change_id', sa.String(length=100), nullable=True))
    op.add_column('remediation_tasks', sa.Column('check_id', sa.String(length=50), nullable=True))
    op.add_column('remediation_tasks', sa.Column('owner_id', sa.String(length=100), nullable=True))
    op.add_column('remediation_tasks', sa.Column('severity', sa.String(length=50), nullable=True))
    op.add_column('remediation_tasks', sa.Column('root_cause', sa.String(length=100), nullable=True))
    op.add_column('remediation_tasks', sa.Column('recommended_action', sa.Text(), nullable=True))
    op.add_column('remediation_tasks', sa.Column('action_type', sa.String(length=50), nullable=False))
    op.add_column('remediation_tasks', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    op.add_column('remediation_tasks', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('remediation_tasks', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.add_column('remediation_tasks', sa.Column('verification_started_at', sa.DateTime(), nullable=True))
    op.add_column('remediation_tasks', sa.Column('rejected_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_remediation_tasks_change_id'), 'remediation_tasks', ['change_id'], unique=False)
    op.create_index(op.f('ix_remediation_tasks_check_id'), 'remediation_tasks', ['check_id'], unique=False)
    op.create_foreign_key(None, 'remediation_tasks', 'changes', ['change_id'], ['change_id'])
    op.create_foreign_key(None, 'remediation_tasks', 'compliance_checks', ['check_id'], ['check_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'remediation_tasks', type_='foreignkey')
    op.drop_constraint(None, 'remediation_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_remediation_tasks_check_id'), table_name='remediation_tasks')
    op.drop_index(op.f('ix_remediation_tasks_change_id'), table_name='remediation_tasks')
    op.drop_column('remediation_tasks', 'rejected_at')
    op.drop_column('remediation_tasks', 'verification_started_at')
    op.drop_column('remediation_tasks', 'submitted_at')
    op.drop_column('remediation_tasks', 'started_at')
    op.drop_column('remediation_tasks', 'assigned_at')
    op.drop_column('remediation_tasks', 'action_type')
    op.drop_column('remediation_tasks', 'recommended_action')
    op.drop_column('remediation_tasks', 'root_cause')
    op.drop_column('remediation_tasks', 'severity')
    op.drop_column('remediation_tasks', 'owner_id')
    op.drop_column('remediation_tasks', 'check_id')
    op.drop_column('remediation_tasks', 'change_id')
    op.drop_column('remediation_tasks', 'remediation_id')
    op.drop_column('findings', 'evidence_ids')
    op.drop_column('findings', 'check_result_id')
    op.drop_constraint(None, 'check_result_evidence_association', type_='foreignkey')
    op.drop_constraint(None, 'check_result_evidence_association', type_='foreignkey')
    op.create_foreign_key(None, 'check_result_evidence_association', 'evidence_metadata', ['evidence_id'], ['evidence_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'check_result_evidence_association', 'check_results', ['result_id'], ['result_id'], ondelete='CASCADE')
    op.drop_column('changes', 'monitoring_status')
    op.drop_column('changes', 'last_evaluated_at')
    op.drop_column('changes', 'last_observed_at')
    op.drop_column('changes', 'previous_state_hash')
    op.drop_column('changes', 'state_hash')
    op.drop_column('changes', 'emergency_retro_approved')
    op.drop_column('changes', 'emergency_approved_by')
    op.drop_column('changes', 'emergency_reason')
    op.drop_column('changes', 'is_emergency')
    op.drop_constraint('uq_change_relationship_unique', 'change_relationships', type_='unique')
    op.drop_index(op.f('ix_change_relationships_tenant_id'), table_name='change_relationships')
    op.drop_column('change_relationships', 'relationship_state')
    op.drop_column('change_relationships', 'confidence')
    op.drop_column('change_relationships', 'correlation_evidence')
    op.drop_column('change_relationships', 'correlation_method')
    op.drop_column('change_relationships', 'created_at')
    op.drop_column('change_relationships', 'evidence_reference')
    op.drop_column('change_relationships', 'tenant_id')
    op.create_table('authorizations',
    sa.Column('authorization_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('change_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('authorized_by', sa.VARCHAR(length=100), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('authorized_at', sa.DATETIME(), nullable=False),
    sa.Column('justification', sa.TEXT(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by'], ['users.internal_user_id'], ),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.PrimaryKeyConstraint('authorization_id')
    )
    op.create_index(op.f('ix_authorizations_tenant_id'), 'authorizations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_authorizations_change_id'), 'authorizations', ['change_id'], unique=False)
    op.create_index(op.f('ix_authorizations_authorized_by'), 'authorizations', ['authorized_by'], unique=False)
    op.create_table('check_results',
    sa.Column('result_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('check_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('change_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('result', sa.VARCHAR(length=17), nullable=False),
    sa.Column('rule_version', sa.VARCHAR(length=50), nullable=False),
    sa.Column('evaluation_inputs', sqlite.JSON(), nullable=False),
    sa.Column('details', sqlite.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.ForeignKeyConstraint(['check_id'], ['compliance_checks.check_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_check_results_tenant_id'), 'check_results', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_check_results_check_id'), 'check_results', ['check_id'], unique=False)
    op.create_index(op.f('ix_check_results_change_id'), 'check_results', ['change_id'], unique=False)
    op.create_table('approvals',
    sa.Column('approval_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('change_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('approver_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('decision', sa.VARCHAR(length=50), nullable=False),
    sa.Column('approved_at', sa.DATETIME(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.internal_user_id'], ),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_index(op.f('ix_approvals_tenant_id'), 'approvals', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_approvals_change_id'), 'approvals', ['change_id'], unique=False)
    op.create_index(op.f('ix_approvals_approver_id'), 'approvals', ['approver_id'], unique=False)
    op.create_table('tests',
    sa.Column('test_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('change_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), nullable=False),
    sa.Column('pipeline_id', sa.VARCHAR(length=150), nullable=False),
    sa.Column('commit_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('test_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('evidence_reference', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_index(op.f('ix_tests_tenant_id'), 'tests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tests_change_id'), 'tests', ['change_id'], unique=False)
    op.create_table('evidence_metadata',
    sa.Column('evidence_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('change_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), nullable=False),
    sa.Column('source_record_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('evidence_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('storage_reference', sa.VARCHAR(length=200), nullable=False),
    sa.Column('collected_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_metadata_tenant_id'), 'evidence_metadata', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_evidence_metadata_change_id'), 'evidence_metadata', ['change_id'], unique=False)
    op.create_table('deployments',
    sa.Column('deployment_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('change_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('application_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('environment_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('repository_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), nullable=False),
    sa.Column('commit_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('deployed_by', sa.VARCHAR(length=100), nullable=False),
    sa.Column('deployed_at', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['change_id'], ['changes.change_id'], ),
    sa.ForeignKeyConstraint(['deployed_by'], ['users.internal_user_id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.environment_id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.repository_id'], ),
    sa.PrimaryKeyConstraint('deployment_id')
    )
    op.create_index(op.f('ix_deployments_tenant_id'), 'deployments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_deployments_repository_id'), 'deployments', ['repository_id'], unique=False)
    op.create_index(op.f('ix_deployments_environment_id'), 'deployments', ['environment_id'], unique=False)
    op.create_index(op.f('ix_deployments_deployed_by'), 'deployments', ['deployed_by'], unique=False)
    op.create_index(op.f('ix_deployments_change_id'), 'deployments', ['change_id'], unique=False)
    op.create_index(op.f('ix_deployments_application_id'), 'deployments', ['application_id'], unique=False)
    op.drop_index(op.f('ix_change_tests_tenant_id'), table_name='change_tests')
    op.drop_index(op.f('ix_change_tests_change_id'), table_name='change_tests')
    op.drop_table('change_tests')
    op.drop_index(op.f('ix_change_rollbacks_tenant_id'), table_name='change_rollbacks')
    op.drop_index(op.f('ix_change_rollbacks_change_id'), table_name='change_rollbacks')
    op.drop_table('change_rollbacks')
    op.drop_index(op.f('ix_change_evidence_tenant_id'), table_name='change_evidence')
    op.drop_index(op.f('ix_change_evidence_change_id'), table_name='change_evidence')
    op.drop_table('change_evidence')
    op.drop_index(op.f('ix_change_deployments_tenant_id'), table_name='change_deployments')
    op.drop_index(op.f('ix_change_deployments_repository_id'), table_name='change_deployments')
    op.drop_index(op.f('ix_change_deployments_environment_id'), table_name='change_deployments')
    op.drop_index(op.f('ix_change_deployments_deployed_by'), table_name='change_deployments')
    op.drop_index(op.f('ix_change_deployments_change_id'), table_name='change_deployments')
    op.drop_index(op.f('ix_change_deployments_application_id'), table_name='change_deployments')
    op.drop_table('change_deployments')
    op.drop_index(op.f('ix_change_decisions_tenant_id'), table_name='change_decisions')
    op.drop_index(op.f('ix_change_decisions_change_id'), table_name='change_decisions')
    op.drop_table('change_decisions')
    op.drop_index(op.f('ix_change_check_results_tenant_id'), table_name='change_check_results')
    op.drop_index(op.f('ix_change_check_results_check_id'), table_name='change_check_results')
    op.drop_index(op.f('ix_change_check_results_change_id'), table_name='change_check_results')
    op.drop_table('change_check_results')
    op.drop_index(op.f('ix_change_authorizations_tenant_id'), table_name='change_authorizations')
    op.drop_index(op.f('ix_change_authorizations_change_id'), table_name='change_authorizations')
    op.drop_index(op.f('ix_change_authorizations_authorized_by'), table_name='change_authorizations')
    op.drop_table('change_authorizations')
    op.drop_index(op.f('ix_change_approvals_tenant_id'), table_name='change_approvals')
    op.drop_index(op.f('ix_change_approvals_change_id'), table_name='change_approvals')
    op.drop_index(op.f('ix_change_approvals_approver_id'), table_name='change_approvals')
    op.drop_table('change_approvals')
    # ### end Alembic commands ###
